### ISSUE TITLE
General: If Address 1 field is blank, hide the entire address

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#10]
Affected:
**Header
Pre Footer
Contact Us**

![image](https://cloud.githubusercontent.com/assets/12888048/16723765/ada4e454-4781-11e6-8a3c-5932fb4f8ca1.png)

**Comment by titandigitalaus** [comment]
Not a QA issue - Not Fixing - via Jonathan

**Comment by romatitan** [comment]
Standard/instruction was changed.
