### ISSUE TITLE
Contact Us: Hide the form container if the shortcode field is blank.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#101]
![image](https://cloud.githubusercontent.com/assets/12888048/17286287/35483940-57fb-11e6-8035-c9f085e369b2.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17286296/3eb09f2c-57fb-11e6-8d87-da5f1d21457e.png)

**Comment by devinci** [comment]
Hidden if no shortcode present
