### ISSUE TITLE
About Us: After clicking on the 'About Us' menu, it did not redirect to About Us page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#103]
![image](https://cloud.githubusercontent.com/assets/12888048/17286581/248e4408-57fd-11e6-8843-08acb9d3c131.png)

**Comment by devinci** [comment]
About us is a dropdown. Clicking it will display dropdown menu. Remove sub-menu items to make clickable, or add another about-us into sub-menu

**Comment by titandigitalqa** [comment]
About Us is a basic information page and it is very common for it to have sub pages.
Please check this site:
http://austecelectrical-imp.stage.titanweb.com.au/

**Comment by titandigitalqa** [comment]
For the About Us menu, redirect to its respective page when clicked.
And display the sub-menu when hovered.

**Comment by devinci** [comment]
In regard to your example http://austecelectrical-imp.stage.titanweb.com.au/
Sub menus are not mobile compatible as there is no hover on mobile. Clicking on about-us shows dropdown and routes to about-us page at the same time.

New menu implementation to cater for clickable dropdown that is mobile compatible. 

![image](https://cloud.githubusercontent.com/assets/7167770/17772658/4b5f9d52-654a-11e6-8104-f1557bcc8779.png)
