### ISSUE TITLE
Events/News Single: Bootstrap grid layout error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#104]
![image](https://cloud.githubusercontent.com/assets/12888048/17286711/cd82e6e0-57fd-11e6-9cd5-ca23b4d5a720.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17286697/b5858764-57fd-11e6-8959-e7d41c3bf531.png)

**Comment by devinci** [comment]
restored padding
