### ISSUE TITLE
Homepage - Featured Blog: Bootstrap grid layout error. Featured blogs should be inside the 1140px area.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#108]
**6 col per post (3 col for post image and 3 col for post content)
30px gutter between post**
![image](https://cloud.githubusercontent.com/assets/12888048/17286957/604184cc-57ff-11e6-868e-9b2c40f71d65.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17287038/de42c8a4-57ff-11e6-8e96-10062b813382.png)

**Comment by devinci** [comment]
Adjusted to include padding
