### ISSUE TITLE
Header: Style the sub-menu properly

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#109]
**Please check the sub-menu container, text alignment, font styles, hover and active state.**

![image](https://cloud.githubusercontent.com/assets/12888048/17287113/4bad9770-5800-11e6-8d3f-4fea44f1f1f7.png)

**Example:**
![image](https://cloud.githubusercontent.com/assets/12888048/17287118/51a8dce8-5800-11e6-8a72-74d1eca2217e.png)

**Comment by devinci** [comment]
Styled dropdown
