### ISSUE TITLE
Inner pages: Please remove the page featured image padding-right. It has a 30px margin already.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#111]
![image](https://cloud.githubusercontent.com/assets/12888048/17690812/97decd8e-63c3-11e6-9693-57a585b36a7b.png)

**Comment by devinci** [comment]
Removed 15px of margin to maintain bootstrap grid layout

![image](https://cloud.githubusercontent.com/assets/7167770/17735658/bbdf577e-6483-11e6-99dd-8517436a0c05.png)
