### ISSUE TITLE
Contact Us: Please reduce the height of the map to H: 300px as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#112]
![image](https://cloud.githubusercontent.com/assets/12888048/17690835/c78a922a-63c3-11e6-8648-a607239be250.png)

Please note that when reducing the height of the map, reduce the height of the form as well.
**Contact Us form** and **Contact details section** height are equal in the given design

![image](https://cloud.githubusercontent.com/assets/12888048/17690919/441a4880-63c4-11e6-85fa-52f7c6972928.png)

**Comment by devinci** [comment]
Adjusted map to 300px

![image](https://cloud.githubusercontent.com/assets/7167770/17738550/f24ce304-6491-11e6-9421-d9a6ec255617.png)
