### ISSUE TITLE
Functions: There's an unknown page description displayed in front end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#113]
![image](https://cloud.githubusercontent.com/assets/12888048/17690980/a847d8e0-63c4-11e6-9e8a-ea22c939a43f.png)

**Comment by devinci** [comment]
It is in custom content in section 2  of the functions page in /admin 

![image](https://cloud.githubusercontent.com/assets/7167770/17741878/239be714-649e-11e6-9605-a30105ad1587.png)
