### ISSUE TITLE
General: Garbage characters displayed in front end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#114]
![image](https://cloud.githubusercontent.com/assets/12888048/17691063/104ff954-63c5-11e6-98ad-5fd0956fe679.png)

**Comment by devinci** [comment]
Issue with function in titan-toolbox - fixed

![image](https://cloud.githubusercontent.com/assets/7167770/17739728/542e502c-6496-11e6-8fce-d6f11ae19276.png)
