### ISSUE TITLE
Homepage - Blog: For grid view, adjust the height of the title container based on the longest post title. Align the title, description, and button in a row.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#115]
![image](https://cloud.githubusercontent.com/assets/12888048/17691447/172a1320-63c7-11e6-9586-8c95635a0dd8.png)

**Comment by devinci** [comment]
Adjust to request

![image](https://cloud.githubusercontent.com/assets/7167770/17772581/ef5ac676-6549-11e6-8b3a-afd196733e54.png)
