### ISSUE TITLE
Functions: Paragraphs were displayed together. It should be separated.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#116]
![image](https://cloud.githubusercontent.com/assets/12888048/17692166/f9fbc6be-63ca-11e6-82f0-852b972815fe.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17692179/11461a22-63cb-11e6-80b6-4fe2111f8c27.png)

**Comment by devinci** [comment]
Fixed to separate out into paragraphs

![image](https://cloud.githubusercontent.com/assets/7167770/17766630/55804124-652c-11e6-9358-ce17c4c79f02.png)
