### ISSUE TITLE
Thank You: Breadcrumbs wasn't implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#117]
![image](https://cloud.githubusercontent.com/assets/12888048/17692221/52763784-63cb-11e6-98d7-20d5d17300e5.png)

**Comment by devinci** [comment]
Implemented breadcrumb

![image](https://cloud.githubusercontent.com/assets/7167770/17742583/dbd8ed8e-64a0-11e6-908f-287d63d0db16.png)
