### ISSUE TITLE
Thank You / Error Page: Sidebar wasn't added. If design is not provided, kindly follow the About Us page. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#118]
![image](https://cloud.githubusercontent.com/assets/12888048/17692243/6b809d32-63cb-11e6-8500-9ee35111d5fc.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17692334/dda13e26-63cb-11e6-998b-3dd0ca96ff7a.png)

**Comment by devinci** [comment]
Sidebar added to thank you page

![image](https://cloud.githubusercontent.com/assets/7167770/17742779/a3c28c88-64a1-11e6-8107-e0c7f910ce72.png)

Sidebar added to error page 

![image](https://cloud.githubusercontent.com/assets/7167770/17742810/ca57064e-64a1-11e6-9e88-2e575852f7e1.png)
