### ISSUE TITLE
General: Hide the map if physical address fields are blank

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#12]
Affected
**Contact Us
Pre Footer**

![image](https://cloud.githubusercontent.com/assets/12888048/16723946/a4eb4c80-4782-11e6-916b-87547db253b3.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16723952/ad2b8a86-4782-11e6-8ac6-6ff7f4fa6067.png)

**Comment by titandigitalaus** [comment]
Not a QA issue - Not Fixing - via Jonathan

**Comment by romatitan** [comment]
**Is this a bug. Kindly check again.
If there's no address, the map should be hidden.**

![image](https://cloud.githubusercontent.com/assets/12888048/17239814/8c93a108-5599-11e6-842b-67d6d8f079dc.png)

**Comment by devinci** [comment]
Map hidden if fields are blank

**Comment by romatitan** [comment]
**Kindly check again in Contact Us page**
