### ISSUE TITLE
Sitemap: Incorrect sidebar alignment. Align it with the page content.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#120]
![image](https://cloud.githubusercontent.com/assets/12888048/17692309/b876c6fc-63cb-11e6-9527-ddb43fde20ac.png)

**Comment by devinci** [comment]
Adjusted to align to content 

![image](https://cloud.githubusercontent.com/assets/7167770/17742290/b0596c16-649f-11e6-900b-dcd8f54f388c.png)
