### ISSUE TITLE
Events/News Single: Incorrect breadcrumbs trail.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#121]
For Events Single page: **home/events/events single page**
For News Single page: **home/news/news single page**

![image](https://cloud.githubusercontent.com/assets/12888048/17692397/32d0b840-63cc-11e6-9c31-649bd3824134.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17692399/34dc8cea-63cc-11e6-8ed9-1f36938bd1a0.png)

**Comment by devinci** [comment]
For posts to display their parent page, the plugin used for this requires the post to have it's parent set in WP shown below.

![image](https://cloud.githubusercontent.com/assets/7167770/17766791/20441476-652d-11e6-8628-b2b3b69cddac.png)

![image](https://cloud.githubusercontent.com/assets/7167770/17766830/44d27616-652d-11e6-816b-ea707093109f.png)

**Comment by romatitan** [comment]
It will be a hassle for the client to set the "**parent**" every time they will create a post.
We have **Events** and **News** post category so the breadcrumbs trail can be,
home/**post category**/ post single page
Please let me know your thoughts about this.

**Comment by devinci** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/7167770/17919689/a6c7bfba-69cf-11e6-8ce6-3e3c8cb97a20.png)

![image](https://cloud.githubusercontent.com/assets/7167770/17919752/f80ed520-69cf-11e6-810e-240d776e298e.png)

**Comment by romatitan** [comment]
**Implementor created an Events custom post.
The previous implementation, Events is one of the categories of default post.**
