### ISSUE TITLE
Contact Us: Phone numbers must have area code in brackets - example: (08) 9242 5255

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#122]
![image](https://cloud.githubusercontent.com/assets/12888048/17692461/72f78ba6-63cc-11e6-86a5-47246317ec16.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17692475/8639be78-63cc-11e6-9783-376ca6bc3a5c.png)

**Comment by devinci** [comment]
Added brackets into phone number - be aware that design did not have brackets in. Adding brackets to the designed bootstrap layout causes line-break on phone number as was QA'd previously. To prevent line-break issue, details break designed bootstrap layout. 

![image](https://cloud.githubusercontent.com/assets/7167770/17763185/3fa89316-6517-11e6-9398-3248f9289472.png)
