### ISSUE TITLE
Banner: If it is not possible to limit the banner button, please alternate the button styling

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#123]
If it is not possible to limit the banner button, please alternate the button styling
1st button - solid background
2nd button - transparent background
3rd button - solid background
4th button - transparent background
and so on

![image](https://cloud.githubusercontent.com/assets/12888048/17692560/dcf3f1b6-63cc-11e6-94e5-44935fe14814.png)

**Comment by devinci** [comment]
Not implementing - Refer Jonathan

**Comment by romatitan** [comment]
**Enhancement not done.**
