### ISSUE TITLE
Functions: Do not link the items to a single page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#124]
![image](https://cloud.githubusercontent.com/assets/12888048/17694003/4d7d36a2-63d4-11e6-8d1e-ed38808abbd5.png)

**Please remove page link**

![image](https://cloud.githubusercontent.com/assets/12888048/17694056/931a771a-63d4-11e6-84cb-e78f8ae2c76e.png)

**Comment by devinci** [comment]
Removed link to single page

**Comment by devinci** [comment]
![image](https://cloud.githubusercontent.com/assets/7167770/17742458/638cb9b4-64a0-11e6-8a19-14bbd6cbe446.png)
