### ISSUE TITLE
Events & News: Image is not responsive when resizing the browser, 990px - 1199px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#128]
![image](https://cloud.githubusercontent.com/assets/12888048/17695074/814b7534-63d9-11e6-9028-e067a237ce6e.png)

**Comment by devinci** [comment]
adjusted images to maintain aspect-ratio at this range

![image](https://cloud.githubusercontent.com/assets/7167770/17743496/3002472c-64a4-11e6-8a3f-e5b5623faa4b.png)
