### ISSUE TITLE
Pre Footer: If business detail fields are blank, do not display the respective heading for that specific field.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#13]
Reference link: https://knowledgebase.titanweb.com.au/implementation/gravity-forms-implementation/business-details
![image](https://cloud.githubusercontent.com/assets/12888048/16723996/f88d3c54-4782-11e6-8db4-c5f8d43b09dd.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16723968/ce448f1a-4782-11e6-9ae4-1b5511ff7d48.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16723971/d0ebf780-4782-11e6-82da-4ccd5f37bcfc.png)

**Comment by devinci** [comment]
Fixed
