### ISSUE TITLE
Gallery: Unused space, 767px and below

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#130]
You can still display 2 columns of images in this resolution.
Display images in 1 column for the smaller resolution.
And please, align it properly to center.

![image](https://cloud.githubusercontent.com/assets/12888048/17695266/5ffb0eac-63da-11e6-8479-ff9f3a5d5f2f.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17695287/711df172-63da-11e6-8811-407b0983eff8.png)

**Comment by devinci** [comment]
Adjusted images to be responsive: full-width at xsmall range (320-768)
Unable to display more than one image in this range without causing cascade issues.

![image](https://cloud.githubusercontent.com/assets/7167770/17741084/3a68854a-649b-11e6-96c8-f608f0cf5deb.png)
