### ISSUE TITLE
Contact Us: Please do not zoom in the map too much at first. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#132]
**The user can zoom in, or zoom out the map if they want.**

![image](https://cloud.githubusercontent.com/assets/12888048/17695694/54eede2e-63dc-11e6-903f-ed6510cf2775.png)

**Comment by devinci** [comment]
Adjusted map zoom

![image](https://cloud.githubusercontent.com/assets/7167770/17762387/6731fca8-6510-11e6-88f4-9676f309062f.png)
