### ISSUE TITLE
Gallery: Image is too big and blurred, 767px - -

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#133]
**Here's a previous project you might find helpful for the gallery page, or how the images respond when resizing the browser.**
URL: http://sms-training-imp.stage.titanweb.com.au/gallery/

![image](https://cloud.githubusercontent.com/assets/12888048/17802852/4305210a-6625-11e6-891e-d3759bdfa4c5.png)

**Comment by devinci** [comment]
Changes number of images to display on mobile to 2 in WP gallery page.

![image](https://cloud.githubusercontent.com/assets/7167770/17857488/2fff13e0-6882-11e6-9efb-235394372574.png)
