### ISSUE TITLE
Lead-ins: Please display up to 3 lines of lead-ins title

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#134]
![image](https://cloud.githubusercontent.com/assets/12888048/17803339/6e64c712-6628-11e6-9993-7fc9d9690c58.png)

**Comment by devinci** [comment]
Adjusted to 3 lines

![image](https://cloud.githubusercontent.com/assets/7167770/17858247/41eed8da-6885-11e6-9dc3-2c21c6d65196.png)
