### ISSUE TITLE
Menu: Please display up to 2 lines of menu title

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#135]
![image](https://cloud.githubusercontent.com/assets/12888048/17803360/8ea47f22-6628-11e6-8d65-85deaf5b84a1.png)

**Comment by devinci** [comment]
Adjusted to two lines

![image](https://cloud.githubusercontent.com/assets/7167770/17857818/8e4f3622-6883-11e6-977e-413802aa8718.png)
