### ISSUE TITLE
Thank You / Error Page: Please removed sidebar in accordance with the new standard.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#136]
Note: 
My apologies, but we have a new standard regarding Thank You and Error Page.
If the design is not provided, it will follow the default layout which is full width.

**Comment by devinci** [comment]
Removed sidebar for pages and made content full width. Adjusted img from 50% content width to 35% to avoid stretching. 

![image](https://cloud.githubusercontent.com/assets/7167770/17846935/abfc17d6-684b-11e6-8638-6ebefac5de7b.png)


![image](https://cloud.githubusercontent.com/assets/7167770/17846895/74577dfc-684b-11e6-8b60-7c00f5054f6f.png)
