### ISSUE TITLE
Pre Footer: Do not display the "Email Us" if email field is blank

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#14]
![image](https://cloud.githubusercontent.com/assets/12888048/16724031/19add86c-4783-11e6-91e1-382384e33b7a.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16724039/28002adc-4783-11e6-8f8a-9c0e637e6d14.png)

**Comment by devinci** [comment]
Fixed
