### ISSUE TITLE
Menu: Overlapping menu items

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#140]
Browser: **IE11**

![image](https://cloud.githubusercontent.com/assets/12888048/17805470/450d88cc-6632-11e6-9216-53010b665f6b.png)

**Comment by devinci** [comment]
Fixed menu overlap

![image](https://cloud.githubusercontent.com/assets/7167770/17845921/c5225cc6-6845-11e6-986f-4a2d1679498f.png)
