### ISSUE TITLE
Menu: In the given design menu item width is equal to 4 col. Please check again.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#141]
![image](https://cloud.githubusercontent.com/assets/12888048/17805517/77877998-6632-11e6-8413-0061ecc1264f.png)

**Comment by devinci** [comment]
Adjusted to 4 cols

![image](https://cloud.githubusercontent.com/assets/7167770/17846229/a468e1e2-6847-11e6-91c4-2bcc7872affd.png)
