### ISSUE TITLE
All Forms: IE11 - For fields did not display a highlighted border as error prompt that makes it inconsistent with other browser

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#142]
Browser: **IE11** 

![image](https://cloud.githubusercontent.com/assets/12888048/17805743/86921c26-6633-11e6-9069-47ea97bdbdcf.png)

**Note:**  
For form fields error prompt, You can actually remove the red field effect.
![image](https://cloud.githubusercontent.com/assets/12888048/17805706/5bbe42a4-6633-11e6-8fe6-2b7da0abb30b.png)

**Comment by devinci** [comment]
Managed to get cross-browser consistency for animation of bg color and border

![image](https://cloud.githubusercontent.com/assets/7167770/17883474/fc78adb0-6912-11e6-8eb4-2b258ad3c7cf.png)


Kept both - Jonathan
