### ISSUE TITLE
Users: Incorrect email address. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#16]
**Reference:** https://knowledgebase.titanweb.com.au/implementation/user-accounts/client-user-account
![image](https://cloud.githubusercontent.com/assets/12888048/16724449/534edab0-4785-11e6-81a1-c63aaf1787a1.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16724295/9fa8f8ba-4784-11e6-8dec-36d5280fbc44.png)

**Comment by devinci** [comment]
Added user JJkings - password in Scope doc
