### ISSUE TITLE
The banner title used H1 heading. Only page title should be set to H1

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#19]
Only page title should be set to H1
![image](https://cloud.githubusercontent.com/assets/12888048/16725209/ce1aa19a-4788-11e6-8b42-3c9421d2d96d.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16725186/b822c21e-4788-11e6-8d6b-8b96e2d40221.png)

**Comment by devinci** [comment]
Changed to h2
