### ISSUE TITLE
Admin Options: Broken login logo (image)

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#2]
![image](https://cloud.githubusercontent.com/assets/12888048/16720795/52565f5c-476c-11e6-93a5-89c048e17fb3.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/17241535/c9943fda-55a4-11e6-9fa9-420959a5bb18.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17241541/d034bd56-55a4-11e6-9193-94a95bf3a3bd.png)

**Comment by devinci** [comment]
Updated wp-content
