### ISSUE TITLE
Banner content overflow. Limit the title to 1 line, and description to 3 lines as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#21]
![banner1](https://cloud.githubusercontent.com/assets/12888048/16725736/3d78a7d8-478b-11e6-9426-18cd87aba9e5.jpg)

**Comment by devinci** [comment]
Limits are not implemented - via Jonathan
Overflow will be hidden.

**Comment by romatitan** [comment]
Follow the given design. Restrict the title to 1 line.

**Comment by devinci** [comment]
No line limit restrictions are being implemented - refer to Jonathan

**Comment by romatitan** [comment]
**The new standard is not yet finalized.
And this project still follows our existing standard.**

**Comment by devinci** [comment]
Truncates title to 1 line and description to 3
