### ISSUE TITLE
Banner rotate/slide after 8 seconds. The duration for each Banner item before rotating will be 5 seconds / 5000 ms.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#22]
Reference: https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners
![image](https://cloud.githubusercontent.com/assets/12888048/16725922/3cc1402e-478c-11e6-8d8c-a664dd97a7e2.png)

**Comment by devinci** [comment]
Changed to 5s.
