### ISSUE TITLE
Banner: The banner did not follow the bootstrap grid layout, 1140px area and 30px gutter (15px each side)

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#23]
![image](https://cloud.githubusercontent.com/assets/12888048/16726300/0ec7718c-478e-11e6-80e0-479b3b985c91.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16726308/19035918-478e-11e6-862b-b7269769d52d.png)

**Comment by devinci** [comment]
Fixed via another bug

**Comment by romatitan** [comment]
**Kindly check again.
The banner extends outside the 1170px bootstrap grid.
Banner area should be 1140px only**

![image](https://cloud.githubusercontent.com/assets/12888048/17245925/7e17f954-55bb-11e6-91b4-11830893e52c.png)
