### ISSUE TITLE
Banner: Add a banner image instruction.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#25]
![image](https://cloud.githubusercontent.com/assets/12888048/16727670/bf9b0a36-4794-11e6-81b2-cb7f618f6445.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16727721/fb89057a-4794-11e6-8db0-261644ec9e2f.png)

**Comment by devinci** [comment]
Implemented
