### ISSUE TITLE
Homepage: Button leads to About Us page was not implemented.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#29]
**Create ACFs for homepage button
1. Button text (ACF text)
2. Button Link (ACF page link)**

![image](https://cloud.githubusercontent.com/assets/12888048/16755795/e88eac60-4832-11e6-8e41-813f78772d5e.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16728081/f39ce38e-4796-11e6-9c8f-61bad31e4b86.png)
![homepage](https://cloud.githubusercontent.com/assets/12888048/16728090/05e0314a-4797-11e6-902f-379b8557e5ef.jpg)

**Comment by devinci** [comment]
Implemented button
