### ISSUE TITLE
Admin - Login: TitanDigital logo did not display in frontend

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#3]
![image](https://cloud.githubusercontent.com/assets/12888048/16720813/76183f96-476c-11e6-90aa-cd2efeed0723.png)

**Comment by titandigitalaus** [comment]
Uses the transparent logo. Changed to default titan logo. - Fixed

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/17241541/d034bd56-55a4-11e6-9193-94a95bf3a3bd.png)
