### ISSUE TITLE
Homepage: It did not follow the bootstrap grid layout, 1140px area and 30px gutter (15px each side) 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#30]
Kindly check. the following:
**1. Homepage content**
A 15px gutter on the left side should be maintained.
Content area is 7 col
**2. Lead-in Section 1**
The size of the lead-ins should be adjusted.
A 15px gutter on the right side should be maintained.

**Homepage page content and Lead-in Section 1**
![image](https://cloud.githubusercontent.com/assets/12888048/16728209/a4d85c28-4797-11e6-9e20-310e5f80e82c.png)

**Comment by devinci** [comment]
30px missing from design - Container without outer-gutter should be 1170px - hence 15px extra each side.

Content is 7 col.
Lead in sections 2 & 3 are 6 col with 30px gutters

**Comment by romatitan** [comment]
Please ensure that the 15px gutter on both sides of the page is implemented.
**The home page content already extends outside the 1140px bootstrap grid area.**
Kindly check and please fix the issue.

![image](https://cloud.githubusercontent.com/assets/12888048/17240060/61c00b40-559b-11e6-91ea-c3628275b6ff.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17240164/22c91372-559c-11e6-89d0-d78c6a1ed1a2.png)

**Comment by devinci** [comment]
Adjusted to 1140px content area.

**Comment by romatitan** [comment]
**The lead-ins already extend outside the 1140px bootstrap grid area.**
Please ensure that the 15px gutter on both sides of the page is implemented.
Kindly check and please fix the issue.

![image](https://cloud.githubusercontent.com/assets/12888048/17688730/693e2010-63b4-11e6-8db3-136d35cc2671.png)

**Comment by devinci** [comment]
![image](https://cloud.githubusercontent.com/assets/7167770/17729921/c2825a3a-6466-11e6-9dd8-bccaa1432075.png)
