### ISSUE TITLE
Homepage - Featured Blog: If field is blank, hide the text

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#32]
**Subtitle**
![image](https://cloud.githubusercontent.com/assets/12888048/16728878/a29f1db2-479b-11e6-8e75-010f383aaa7e.png)

**Title**
![image](https://cloud.githubusercontent.com/assets/12888048/16728882/a61dadfa-479b-11e6-95bd-536cbc5edc16.png)

**Comment by devinci** [comment]
Added
