### ISSUE TITLE
General: Separate pages were created for Events and News. There should be only one.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#35]
![image](https://cloud.githubusercontent.com/assets/12888048/16756063/03a5bc30-4835-11e6-8296-825ea22574cd.png)

**Design**
![06-jjk-events-news](https://cloud.githubusercontent.com/assets/12888048/16756071/114a0792-4835-11e6-80ac-37a54ceff9ed.jpg)

**Comment by devinci** [comment]
Conferred with PM (Bill Heppard) & Jolene, separate pages were agreed on to increase prominence of events compared to news.

**Comment by romatitan** [comment]
This will be a change request, not an invalid or scope error.
