### ISSUE TITLE
Pre Footer: Misalignment of contact details and its container. Kindly follow the approved design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#38]
![image](https://cloud.githubusercontent.com/assets/12888048/16756316/e67b5014-4836-11e6-914d-cde633897776.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16756320/e91c2dde-4836-11e6-8a8a-8f67a5b57d51.png)

**Comment by devinci** [comment]
Technically not possible due to the method of implementation used to generate the info box.

**Comment by romatitan** [comment]
Not fixed.

**Comment by devinci** [comment]
Positioned based on compatibility with mobile displays as generating the info bubble for multiple displays requires additional logic functions. - Not fixing

**Comment by romatitan** [comment]
Won't fix.
