### ISSUE TITLE
Homepage - Featured Blog: Allow the post title up to 2 lines only as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#40]
![image](https://cloud.githubusercontent.com/assets/12888048/16756444/a8e74b4e-4837-11e6-9ca3-571e7264e9d8.png)

**Comment by devinci** [comment]
Limits are not implemented - via Jonathan

**Comment by romatitan** [comment]
Not fixed.
It can be implemented.

**Comment by devinci** [comment]
Truncated to 2 lines

**Comment by romatitan** [comment]
**Displayed post full title**
