### ISSUE TITLE
Homepage - Featured Blog: Allow the post description up to 4 lines as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#41]
![image](https://cloud.githubusercontent.com/assets/12888048/16756505/31a8f91e-4838-11e6-8792-c737a812c9ad.png)

**Comment by devinci** [comment]
Limits are not implemented - via Jonathan

**Comment by romatitan** [comment]
Not fix.
It can be implemented

**Comment by romatitan** [comment]
**Displayed description up to 4 lines.**
