### ISSUE TITLE
Inner pages: Incorrect font-family, weight and size for UL and OL content. It should be Source Sans Pro, Light, and 16px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#43]
**OL content**
![image](https://cloud.githubusercontent.com/assets/12888048/16757015/ce7d1fb0-483b-11e6-99a3-01d1fbeb7b27.png)

**UL content**
![image](https://cloud.githubusercontent.com/assets/12888048/16757026/e821b48a-483b-11e6-8ad8-7316ac85ba91.png)

**Comment by devinci** [comment]
Changed to source sans pro light 16px

**Comment by romatitan** [comment]
**Can't verify if the issue was fixed on the following pages because the page description did not display on front-end.
Functions page
Events page
News page
Testimonials page
Gallery page
Privacy Policy
Thank You**

**Comment by romatitan** [comment]
**Can't verify if the issue was fixed on the following pages because the page description did not display on front-end.
Functions page
Events page
News page
Testimonials page
Gallery page
Privacy Policy
Thank You**

**Comment by devinci** [comment]
Need to add default-content section in WP to see the content there

**Comment by romatitan** [comment]
**This issue #93 should be fixed first to be able to verify if UL bullets are styled accordingly.**
