### ISSUE TITLE
Inner pages: Incorrect headings font-family, weight and size.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#44]
**Design:**
Font-family: Source Sans Pro
Font-weight: Bold 
Font size:
H2 - 22px
H3 - 20px
H4 - 18px
H5 - 16px
H6 -14px

![image](https://cloud.githubusercontent.com/assets/12888048/16757079/40595c20-483c-11e6-9620-5461630bd98e.png)

**Comment by devinci** [comment]
Changed headings to source sans pro bold and appropriate sizes.

**Comment by romatitan** [comment]
**Kindly check again the H2 heading on the following page.**
Font-family: Source Sans Pro
Font-weight: Bold 
Font size:
H2 - 22px

**Homepage
Testimonials items
Contact Us page**

**Comment by devinci** [comment]
Adjusted for those pages

**Comment by romatitan** [comment]
**Kindly check again the H2 heading on the following page.**
Font-family: Source Sans Pro
Font-weight: Bold 
Font size:
H2 - 22px

**Homepage
Testimonials items
Contact Us page**

**Comment by romatitan** [comment]
**Kindly check again the H2 heading on Testimonials items(repeater).**
Font-family: Source Sans Pro
Font-weight: Bold 
Font size:
H2 - 22px

**Comment by devinci** [comment]
Fixed for Testimonials - Author class added to identify tag. 

![image](https://cloud.githubusercontent.com/assets/7167770/17731800/49e450d4-646f-11e6-989b-28499a24c4c3.png)

Fixed for Events/News/Functions
Font-family: Source Sans Pro
Font-weight: Bold 
Font size: H2 - 22px

![image](https://cloud.githubusercontent.com/assets/7167770/17732692/5c85b012-6473-11e6-92e9-ef9ab99209f9.png)
