### ISSUE TITLE
Inner pages: Inconsistent size of the page featured image. For page featured image size, kindly follow the image on About Us page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#45]
**About Us, Catering,** 
![image](https://cloud.githubusercontent.com/assets/12888048/16757124/8d1a28b4-483c-11e6-86c3-9e63f0c2b343.png)

**Menu, Functions, Events, News, Testimonials, Gallery, Privacy Policy, Sitemap, Thank You**
![image](https://cloud.githubusercontent.com/assets/12888048/16757125/8ea0e894-483c-11e6-9b02-8e44f50cfd62.png)

**Comment by devinci** [comment]
Adjusted to match about us

**Comment by romatitan** [comment]
**Kindly check again the following pages:
Sitemap
Privacy Policy
Thank You page**

![image](https://cloud.githubusercontent.com/assets/12888048/17284231/7b62a1a0-57eb-11e6-8e06-8e14be69ed86.png)

**Comment by devinci** [comment]
Adjusted to match about us

**Comment by romatitan** [comment]
**Kindly check again the following pages:
Sitemap
Privacy Policy
Thank You page**

![image](https://cloud.githubusercontent.com/assets/12888048/17284231/7b62a1a0-57eb-11e6-8e06-8e14be69ed86.png)
