### ISSUE TITLE
General: Alphabetical OL was displayed as numbers

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#46]
![image](https://cloud.githubusercontent.com/assets/12888048/16757330/c3ea6d1c-483d-11e6-9b24-93584ce2ad4e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16757351/ddb53f1a-483d-11e6-91d2-98ebf3164d8d.png)

**Comment by devinci** [comment]
When wanting to use a list of a different type. In the WP content editor, under the text tab. Specify the "Type" in the ordered list. See link for types (http://www.w3schools.com/tags/att_ol_type.asp)

![image](https://cloud.githubusercontent.com/assets/7167770/17048203/60291798-4fe4-11e6-82ad-448d042d0646.png)

**Comment by romatitan** [comment]
Kindly check the above screenshots.
The "Template" content use for testing consist of OL (numerical and alphabetical), UL and paragraph.
When you copy the template content and paste it into the WYSIWYG editor, the alphabetical OL was displayed as numerical OL and the same in the front-end.

**Backend - WYSIWYG**
![image](https://cloud.githubusercontent.com/assets/20430259/17099674/700aa39c-529c-11e6-950d-22d22b1ab497.png)

**Here's an EXAMPLE from a previous project, though alphabetical OL was displayed as numerical OL in backend, you can see that it was displayed as alphabetical OL in front-end.**

![image](https://cloud.githubusercontent.com/assets/20430259/17099839/77705c66-529d-11e6-876d-32ca776c7ba8.png)

**Comment by romatitan** [comment]
won't fix.
