### ISSUE TITLE
General: UL bullets aren't styled according to the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#47]
**Affected pages & post:**
Homepage
Functions post
Events post
News post
Testimonials page
Testimonials repeater description
Sitemap

![image](https://cloud.githubusercontent.com/assets/12888048/16757400/5fcc034e-483e-11e6-94ca-93e4f567a282.png)

**Comment by devinci** [comment]
Added style for all pages ul bullets

**Comment by romatitan** [comment]
**Can't verify if fixed on the following pages because the page description did not display in front-end.**
**Functions
Events
News
Gallery
Thank You
Privacy Page**

**Comment by devinci** [comment]
Need to add default-content section in WP to see the content there

**Comment by romatitan** [comment]
**This issue #93 should be fixed first to be able to verify if UL bullets are styled accordingly.**
