### ISSUE TITLE
General: Incorrect width of the page featured image. Maintain 30px gutter between the image and page description.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#49]
**Kindly check this related issue #45** 
![image](https://cloud.githubusercontent.com/assets/12888048/16757666/055f7d58-4840-11e6-9d1e-8dadf6f7f184.png)

**Comment by devinci** [comment]
Adjusted to match

**Comment by romatitan** [comment]
**Kindly check again the following pages:
Sitemap
Privacy Policy
Thank You page**

![image](https://cloud.githubusercontent.com/assets/12888048/17284231/7b62a1a0-57eb-11e6-8e06-8e14be69ed86.png)

**Comment by romatitan** [comment]
**Kindly check again the following pages:
Sitemap
Privacy Policy
Thank You page**
