### ISSUE TITLE
Banner: Limit the button (Call to Action Link repeater) up to 2 items only as per the given design

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#5]
![image](https://cloud.githubusercontent.com/assets/12888048/16721170/c12c2558-476f-11e6-858a-a3a784d57f9e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16721181/d2901f2a-476f-11e6-8e7b-976562784c98.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16755737/5eb446e4-4832-11e6-8fe0-39774ac9588a.png)

**Comment by devinci** [comment]
Limits are not implementable - Via Johnathan
