### ISSUE TITLE
General: Incorrect form sidebar implemented for the following pages below. It should be the "Contact Us Today" form sidebar as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#50]
**Affected pages:**
 Events/News
Events/News single
Testimonials 
Gallery
Privacy Policy 
Sitemap

**Comment by devinci** [comment]
Conferred with PM (Bill Heppard) to contact client and query the forms. Responded with request for current layout.

"Hi Sean
Can we please have the booking form on all pages apart from functions, catering and contact us?
This is so the customers can enquire about functions and catering whilst all other pages lead the customer to book.
This is a slight change in what goes where, but we are still going to need the 3 forms.
Thanks for asking for clarification." - Bill Heppard 06/09/2016
