### ISSUE TITLE
General - Forms: Remove the EXTRA field below the Message field

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#51]
![image](https://cloud.githubusercontent.com/assets/12888048/16760501/a9ee67ae-484e-11e6-9bca-b15597b1cea8.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16760502/abb8f9e6-484e-11e6-840b-0521c6daf926.png)
![form](https://cloud.githubusercontent.com/assets/12888048/16760521/bf094c9e-484e-11e6-8f3b-e0a2204398c9.jpg)

**Comment by devinci** [comment]
Removed extra field
