### ISSUE TITLE
General - Forms: There's no left & right padding on fields

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#52]
![image](https://cloud.githubusercontent.com/assets/12888048/16760670/6ba0e37c-484f-11e6-9832-e76c58371bce.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16760674/7252ac1e-484f-11e6-93b7-d0c81edc033e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16760686/7d870e90-484f-11e6-9703-318f4a73f846.png)

**Comment by devinci** [comment]
Added 5px padding. Specify if a different amount is wanted.

**Comment by romatitan** [comment]
**Right padding was not implemented**
![image](https://cloud.githubusercontent.com/assets/12888048/17246955/082e330a-55c2-11e6-92d7-d8cbcfa73866.png)

**Comment by devinci** [comment]
added padding for right

**Comment by romatitan** [comment]
**Right padding was not implemented**
![image](https://cloud.githubusercontent.com/assets/12888048/17246955/082e330a-55c2-11e6-92d7-d8cbcfa73866.png)

**Comment by romatitan** [comment]
**Please check again the Contact Us form fields (contact us page).**

**Comment by devinci** [comment]
![image](https://cloud.githubusercontent.com/assets/7167770/17729889/9516151e-6466-11e6-8064-7618f7fe13ed.png)
