### ISSUE TITLE
Menu: PDF needs to use the file ACF type instead of the URL type.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#53]
![image](https://cloud.githubusercontent.com/assets/12888048/16761872/b970a4c0-4854-11e6-860f-ecb0f2b4859f.png)

**Comment by devinci** [comment]
Changed link field to have a download option - then user can select file to link as download

**Comment by romatitan** [comment]
It should be a **FILE ACF type** on each repeater, not URL or external link
![image](https://cloud.githubusercontent.com/assets/12888048/17247032/a31e87d4-55c2-11e6-9cb8-2674af9d0241.png)

**Comment by devinci** [comment]
**If download is selected, then field changes to file ACF.**
![image](https://cloud.githubusercontent.com/assets/7167770/17439712/9d802406-5b29-11e6-9347-20e039acda84.png)
