### ISSUE TITLE
Menu: Not enough margin between rows of menu. It should be at least 27px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#56]
![image](https://cloud.githubusercontent.com/assets/12888048/16762239/3d4efb88-4856-11e6-82af-5f7702f2005c.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16762243/45fd23d6-4856-11e6-9d6d-3b1a067ca2c9.png)

**Comment by devinci** [comment]
Adjusted margin to 27px
