### ISSUE TITLE
Lead-ins Section1: Limit the lead-ins up to 3 items only as per client request

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#6]
![image](https://cloud.githubusercontent.com/assets/12888048/16755767/9c05dfe4-4832-11e6-8be4-49873378c917.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16721706/d4752692-4773-11e6-8dc7-c0bcb5e0bb26.png)

![image](https://cloud.githubusercontent.com/assets/12888048/16721611/3c0af4ae-4773-11e6-950c-8d81cb4399d4.png)

**Comment by devinci** [comment]
Was changed to 4 to allow for separate news / events pages to include event prominance 
- No "limits" are specified

**Comment by romatitan** [comment]
Only 3 lead-ins are requested by the client. And only 3 lead-ins are in the given design.
Unable to  limit or restrict the number of repeater/lead-ins is a **build issue.**
