### ISSUE TITLE
Functions: Bootstrap grid layout error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#60]
![functions](https://cloud.githubusercontent.com/assets/12888048/16762685/20f9acce-4858-11e6-8879-c1630911910b.jpg)

**Comment by devinci** [comment]
Adjusted to match as close as possible - img will still extends into the gutter

**Comment by romatitan** [comment]
Kindly check again.
**4 col - post image** - related issue #59 
**30px gutter between the image and content.
4 col - post content (title, description, button)**

![image](https://cloud.githubusercontent.com/assets/12888048/17247330/130e8f92-55c5-11e6-91c9-eb803d27dd47.png)

**Comment by romatitan** [comment]
Kindly check again.
Please not that the bootstrap error is for the **Function page**
