### ISSUE TITLE
Functions: Remove button. There's no button in the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#61]
![image](https://cloud.githubusercontent.com/assets/12888048/16762706/3ec210fc-4858-11e6-8fad-9c976ffd52be.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16762712/466908b0-4858-11e6-8f5f-380455489720.png)

**Comment by devinci** [comment]
As functions has a single-page for each function, button is required to reach single-page.

**Comment by romatitan** [comment]
This is not a design error or an invalid issue.
If a button is not included in the given design, it only means that the **title/image** will be used to link the post to its single page.

**Comment by devinci** [comment]
Removed button and added link to whole post.

**Comment by romatitan** [comment]
**Kindly check again.**
