### ISSUE TITLE
Functions: List items should be a repeater, not post.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#64]
![image](https://cloud.githubusercontent.com/assets/12888048/16762963/5eeb46d6-4859-11e6-82a4-2a3e9ae12ad3.png)

**Comment by devinci** [comment]
All functionality is the same as is provided by post type, repeater not required - Via Jonathan

**Comment by romatitan** [comment]
"All I want for the functions page is a repeater (with no single pages)
So no READ MORE" - Bill Heppard

**Comment by devinci** [comment]
Changed to use repeater
