### ISSUE TITLE
Events/News: Incorrect size of the post image. It should, width = 3col and H:169px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#65]
![image](https://cloud.githubusercontent.com/assets/12888048/16763213/8d34be40-485a-11e6-9a72-8e103fbd2712.png)

**Comment by devinci** [comment]
Adjusted

**Comment by romatitan** [comment]
Not yet fixed.

**Comment by romatitan** [comment]
Not yet fixed.
Kindly check again.
