### ISSUE TITLE
Events/News: Display up to 5 lines of post description

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#68]
![image](https://cloud.githubusercontent.com/assets/12888048/16763464/7866b4a4-485b-11e6-92b1-86bd1ca1ffab.png)

**Comment by devinci** [comment]
Limits are not implemented - via Jonathan

**Comment by romatitan** [comment]
**Post description number of lines will depend on the design.**
Ref: https://knowledgebase.titanweb.com.au/implementation/standard-pages/post-title-and-post-desription


![image](https://cloud.githubusercontent.com/assets/12888048/17240950/2f67dafa-55a1-11e6-8c23-74c88bc684a7.png)

**Comment by romatitan** [comment]
Won't fix.
Testing standards have been changed.
