### ISSUE TITLE
Testimonials: Different quotation marks were implemented.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#69]
![image](https://cloud.githubusercontent.com/assets/12888048/16763596/0f792c8c-485c-11e6-90c8-4f008f01a55e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16763598/117868a4-485c-11e6-940a-c4ab85e4b887.png)

**Comment by devinci** [comment]
Quotation marks were changed to use embedded FontAwesome content else would require svg images - more resources

**Comment by romatitan** [comment]
Won't fix by dev.
