### ISSUE TITLE
Lead-ins Section2: Limit the lead-ins up to 2 items only as per the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#7]
![image](https://cloud.githubusercontent.com/assets/12888048/16721728/0071ca84-4774-11e6-912e-3262cd355952.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16721730/0326ffe2-4774-11e6-9ed2-b38b85b4454a.png)

**Comment by devinci** [comment]
- No "limits" are specified - Via Jonathan

**Comment by romatitan** [comment]
The number of lead-ins should be based on the given design.
Unable to limit or restrict the number of lead-ins is a build issue.
