### ISSUE TITLE
Gallery: Hover state wasn't implemented on images.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#73]
![image](https://cloud.githubusercontent.com/assets/12888048/16763825/4fe7dd62-485d-11e6-9623-57e89cd01e64.png)

**Comment by devinci** [comment]
Implemented scale effect

**Comment by romatitan** [comment]
**Kindly follow the given design.**

**Comment by devinci** [comment]
Adjusted to design
