### ISSUE TITLE
Gallery: Images in fancy box should be able to navigation to both prev and next image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#75]
![image](https://cloud.githubusercontent.com/assets/12888048/16763883/b514268c-485d-11e6-8bff-4f6da5b6b00b.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16763905/cd7be1a6-485d-11e6-8b04-d32ae1392e77.png)

**Comment by devinci** [comment]
They can - when they are not the first or last image.

**Comment by romatitan** [comment]
It should be able to loop.

**Comment by devinci** [comment]
Adjusted to loop
