### ISSUE TITLE
Contact Us: Bootstrap grid layout error 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#76]
![image](https://cloud.githubusercontent.com/assets/12888048/16763993/2bb22280-485e-11e6-9037-8dbc46c80a67.png)

**Comment by devinci** [comment]
Adjusted to col 6 each

**Comment by romatitan** [comment]
**Not yet fixed. Kindly check again.
Form should occupy the 6 col
Contact details section should occupy the 6 col** 

![image](https://cloud.githubusercontent.com/assets/12888048/17284692/9b13afb8-57ef-11e6-8e5a-8cfeefe4e5e2.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17284702/b164ea7a-57ef-11e6-964b-37ae6a22e7d7.png)

**Comment by devinci** [comment]
Adjusted padding
