### ISSUE TITLE
Contact Us: Incorrect height of the contact us form. It should be aligned properly to contact details and map

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#77]
![image](https://cloud.githubusercontent.com/assets/12888048/16764015/60fa5e58-485e-11e6-88cd-bc5400e48122.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764026/73c0fbd2-485e-11e6-890b-6936b5d4bbff.png)

**Comment by devinci** [comment]
Adjusted to same height
