### ISSUE TITLE
General: Add enough margin between page featured image and description

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#78]
![image](https://cloud.githubusercontent.com/assets/12888048/16764157/2224f9da-485f-11e6-8b7d-33a207f241bf.png)

**Comment by devinci** [comment]
Added 50px margin

**Comment by romatitan** [comment]
**Kindly check again on the following pages:
Sitemap
Privacy
Thank You**

**Comment by devinci** [comment]
Styled to match about-us

**Comment by romatitan** [comment]
**Kindly check again on the following pages:
Sitemap
Privacy
Thank You**
