### ISSUE TITLE
General: Add enough margin between page content and listing/repeater/gallery/forms

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#79]
Affected pages:
**Menu
Functions
Events/News
Testimonials
Gallery
Contact Us
Sitemap**

![image](https://cloud.githubusercontent.com/assets/12888048/16764201/62c6333c-485f-11e6-82ca-cd99f5f6d729.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764205/65b47522-485f-11e6-927c-8398f6d16d87.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764209/6e02ee98-485f-11e6-99a6-a9b980668231.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764218/78752f8a-485f-11e6-9719-64a24d9b0209.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764224/8063aafa-485f-11e6-8f0c-dde41d0f3a5e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16764227/88282612-485f-11e6-9c47-08a48b9e7591.png)

**Comment by devinci** [comment]
Added breaker to content section - 50px
