### ISSUE TITLE
General: W3C Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#80]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fjjkings-imp.stage.titanweb.com.au%2F
https://validator.w3.org/nu/?doc=http%3A%2F%2Fjjkings-imp.stage.titanweb.com.au%2Fabout-us%2F

**Comment by devinci** [comment]
aboutUs issue fixed

**Comment by devinci** [comment]
Fixed listed issues

**Comment by romatitan** [comment]
**General -Inner pages: W3C errors**
https://validator.w3.org/nu/?doc=http%3A%2F%2Fjjkings-imp.stage.titanweb.com.au%2Fabout-us%2F

![image](https://cloud.githubusercontent.com/assets/12888048/17284004/403cc0d0-57e9-11e6-83ad-71facd95cab4.png)

**Comment by devinci** [comment]
Above mentioned W3C errors are inherited from Gravity Forms plugin and excluded from modification

**Comment by romatitan** [comment]
**Here's an example previous project which also used gravity form but don't have a W3C Errors.**
Kindly check, please.

https://validator.w3.org/nu/?doc=http%3A%2F%2Fsms-training-imp.stage.titanweb.com.au%2Fabout%2F

**Comment by devinci** [comment]
I have conferred with Jonathan, if it is part of gravity forms source then we don't modify it. These can arise through plugin updates.

**Comment by romatitan** [comment]
Kindly check this site. 
Can you please explain why this site don't display an error about "max length"?
http://leftbank2.stage.titanweb.com.au/functions/

**Comment by romatitan** [comment]
W3C errors regarding "max length" will be flag as plug-in issue.
