### ISSUE TITLE
 Is it needed to display all DAYS' opening hours? In the given design, it only shows MON to SAT and SUNDAY.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#88]
![image](https://cloud.githubusercontent.com/assets/12888048/17243984/0c24dd66-55b2-11e6-859c-72cebfabf0c3.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17243985/0ec7ae5e-55b2-11e6-802e-fd5f00a5cc62.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17243988/117ac15e-55b2-11e6-8e81-d550f045ede6.png)

**Comment by devinci** [comment]
Restricted output of business details to only display MON to SAT and SUNDAY in header and contact-us page
