### ISSUE TITLE
Pre Footer: Incorrect opening hours were displayed on the pre-footer section

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#89]
Front-end: **It displays the first 2 fields with a value from the business details - office hours.**
Design: **MON to SAT and SUNDAY only**

![image](https://cloud.githubusercontent.com/assets/12888048/17244031/4e33c276-55b2-11e6-8dd4-10dcf35f3509.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17244035/5178927c-55b2-11e6-949d-74c930d31a46.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17244038/5483e4b2-55b2-11e6-99cc-559a871fd349.png)

**Comment by romatitan** [comment]
Please check again.
**Opening hours** are the following:
**Mon - Sat** 
**Sunday** 

![image](https://cloud.githubusercontent.com/assets/12888048/17689924/ae92bc76-63bd-11e6-8f85-39ed7ed68e83.png)

**Comment by devinci** [comment]
![image](https://cloud.githubusercontent.com/assets/7167770/17730679/292f71de-646a-11e6-8cb5-db128ecdfe5d.png)
