### ISSUE TITLE
Banner did not pause on mouse hover.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#90]
Ref: https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners

![image](https://cloud.githubusercontent.com/assets/12888048/17245817/f49555a0-55ba-11e6-948f-118c53067062.png)

**Comment by devinci** [comment]
Added pause on hover function fix

**Comment by romatitan** [comment]
**Can't verify if this is fixed.
Please check this #110 issue first .**

**Comment by devinci** [comment]
Fixed as part of #110
