### ISSUE TITLE
General: Page description did not display in front-end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#93]
Affected pages:
**Privacy Policy 
Thank You 
Gallery 
Testimonials 
News 
Events** 

![image](https://cloud.githubusercontent.com/assets/12888048/17246691/44abdde8-55c0-11e6-917e-acefdb291a70.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17246693/49ac9652-55c0-11e6-9431-ca8ec24b8919.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17246699/4fb3004a-55c0-11e6-9394-dd1c6adf2f9a.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17246701/538050c4-55c0-11e6-8ea2-292058190601.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17246706/5875d0d6-55c0-11e6-8afe-ed9a385a4759.png)

![image](https://cloud.githubusercontent.com/assets/12888048/17246708/5c0d33c4-55c0-11e6-90db-850671c8e7be.png)

**Comment by romatitan** [comment]
Please check again on **Testimonial page**

**Comment by devinci** [comment]
Fixed to display content

![image](https://cloud.githubusercontent.com/assets/7167770/17765584/149f0988-6527-11e6-8d65-c229bdbbba26.png)
